### ISSUE TITLE
CMake failure: set_target_properties called with incorrect number of arguments

### ISSUE THREAD

**Issue by markstock** [AMReX-Codes/AMReX-Hydro#88]
I built AMReX 22.04 in 2D double precision, CUDA and OpenMP but no MPI, on a Fedora 31 machine with GCC 9.3.1 and CUDA 11.2 - no problems.

Pulled the latest AMReX-Hydro today and tried to build against it.  CMake 3.17.4 reports:

```
CMake Error at /opt/amrex/22.04-2d/Tools/CMake/AMReXTargetHelpers.cmake:126 (set_target_properties):
   set_target_properties called with incorrect number of arguments.
 Call Stack (most recent call first):
   CMakeLists.txt:105 (setup_target_for_cuda_compilation)
```

That line is

```
set_target_properties( ${_target}
      PROPERTIES
      CUDA_SEPARABLE_COMPILATION ${AMReX_GPU_RDC}      # This adds -dc
   )
```

I'll try with the latest AMReX.

Also, please note in the compilation guide that `AMReX_PRECISION` has to be DOUBLE for AMReX-Hydro to configure.

**Comment by markstock** [comment]
Using AMReX 22.06 fixed the CMake bug. If time allows, versioning AMReX-Hydro alongside AMReX would help potential users. Thanks!

**Comment by etpalmer63** [comment]
Thanks for the feedback Mark and sorry about the trouble. I'll look into requiring a specific version of AMReX with later updates of AMReX-Hydro. 

Erik
