### ISSUE TITLE
BDS with Symmetry Boundary Condition

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/AMReX-Hydro#96]
I have a problem setup involving a symmetry and wall boundary conditions. I wanted to use the BDS limiter but I get an error message saying it isn't setup for those BC types. Is it possible to extend the limiter to work with those BC types? @ajnonaka

**Comment by ajnonaka** [comment]
@ldowen try any problem now, but use AMReX-Hydro branch enable_more_physical_bcs
I think *all* boundary conditions types should work now; in my testing so far everything I've tried seems reasonable.
